// Generated by EmDash CLI
// Do not edit manually - run `emdash types` to regenerate

import type { PortableTextBlock } from "emdash";

export interface CommentClassification {
  id: string;
  slug: string | null;
  status: string;
  comment_id: string;
  classified_by_id: string;
  classification: "best" | "good" | "average" | "hate_speech" | "bullying" | "vulgar" | "spamming" | "expedient" | "peoples_choice";
  sentiment: "positive" | "negative" | "neutral" | "expedient" | "peoples_choice";
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Comment {
  id: string;
  slug: string | null;
  status: string;
  post_id?: string;
  author?: string;
  parent_id?: string;
  content: string;
  guest_name_name?: string;
  guest_author_email?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  author?: string;
  content: PortableTextBlock[];
  type: "article" | "podcast" | "news" | "video" | "community" | "topics" | "mindbytes";
  comment_enabled?: boolean;
  is_editors_pick?: boolean;
  estimated_reading_minutes?: number;
  view_count?: number;
  origin_resource?: string;
  excerpt?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}